"""add field pregnancy_start_date

Revision ID: 08bba30fbdf5
Revises: a661e2e96c92
Create Date: 2026-01-23 15:55:54.765933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '08bba30fbdf5'
down_revision: Union[str, Sequence[str], None] = 'a661e2e96c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_plannedworkout_plan_id'), 'plannedworkout', ['plan_id'], unique=False)
    op.add_column('plannedworkoutexercise', sa.Column('is_modified', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_plannedworkoutexercise_exercise_id'), 'plannedworkoutexercise', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_plannedworkoutexercise_planned_workout_id'), 'plannedworkoutexercise', ['planned_workout_id'], unique=False)
    op.add_column('user', sa.Column('pregnancy_start_date', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute('UPDATE "user" SET role = "user" WHERE role IS NULL;')
    op.alter_column('user', 'role', nullable=False)

    op.drop_column('user', 'current_phase')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_phase', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'role')
    op.drop_column('user', 'pregnancy_start_date')
    op.drop_index(op.f('ix_plannedworkoutexercise_planned_workout_id'), table_name='plannedworkoutexercise')
    op.drop_index(op.f('ix_plannedworkoutexercise_exercise_id'), table_name='plannedworkoutexercise')
    op.drop_column('plannedworkoutexercise', 'is_modified')
    op.drop_index(op.f('ix_plannedworkout_plan_id'), table_name='plannedworkout')
    # ### end Alembic commands ###
