"""initial schema

Revision ID: b1c06aee03a0
Revises: 
Create Date: 2026-01-22 18:44:41.406469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b1c06aee03a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plannedworkoutexercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planned_workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['planned_workout_id'], ['plannedworkout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'completedworkout', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'completedworkout', 'plannedworkout', ['planned_workout_id'], ['id'])
    op.add_column('exercise', sa.Column('primary_muscles', sa.JSON(), nullable=True))
    op.add_column('exercise', sa.Column('contraindications', sa.JSON(), nullable=True))
    op.add_column('exercise', sa.Column('base_rpe', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'plannedworkout', 'trainingplan', ['plan_id'], ['id'])
    op.create_foreign_key(None, 'trainingplan', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trainingplan', type_='foreignkey')
    op.drop_constraint(None, 'plannedworkout', type_='foreignkey')
    op.drop_column('exercise', 'base_rpe')
    op.drop_column('exercise', 'contraindications')
    op.drop_column('exercise', 'primary_muscles')
    op.drop_constraint(None, 'completedworkout', type_='foreignkey')
    op.drop_constraint(None, 'completedworkout', type_='foreignkey')
    op.drop_table('plannedworkoutexercise')
    # ### end Alembic commands ###
