"""update user

Revision ID: b75fd3880a94
Revises: bc1407577cfe
Create Date: 2026-01-29 12:52:31.271554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

experience_enum = postgresql.ENUM(
    "beginner",
    "intermediate",
    "advanced",
    name="experiencelevel",
)

# revision identifiers, used by Alembic.
revision: str = 'b75fd3880a94'
down_revision: Union[str, Sequence[str], None] = 'bc1407577cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    experience_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column(
        "user",
        "experience_level",
        type_=experience_enum,
        existing_type=sa.String(),
        postgresql_using="experience_level::experiencelevel",
    )
    op.drop_column('user', 'due_date')
    op.drop_column('user', 'pregnancy_start_date')
    op.add_column('userprofile', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('userprofile', sa.Column('pregnancy_start_date', sa.Date(), nullable=True))
    op.add_column('userprofile', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('userprofile', sa.Column('training_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('userprofile', 'equipment',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('userprofile', 'contraindications',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userprofile', 'contraindications',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('userprofile', 'equipment',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('userprofile', 'training_goals')
    op.drop_column('userprofile', 'due_date')
    op.drop_column('userprofile', 'pregnancy_start_date')
    op.drop_column('userprofile', 'full_name')
    op.add_column('user', sa.Column('pregnancy_start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True))
    op.alter_column(
        "user",
        "experience_level",
        type_=sa.String(),
        existing_type=experience_enum,
    )
    experience_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
