"""add is_active and exercisecategory safely

Revision ID: bd1ad4f8c5c4
Revises: 3e9015daf3c4
Create Date: 2026-01-23 00:26:13.440918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bd1ad4f8c5c4'
down_revision: Union[str, Sequence[str], None] = '3e9015daf3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
