"""initial schema

Revision ID: c40d32178873
Revises: b1c06aee03a0
Create Date: 2026-01-22 19:19:39.675456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c40d32178873'
down_revision: Union[str, Sequence[str], None] = 'b1c06aee03a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('base_sets', sa.Integer(), nullable=False))
    op.add_column('exercise', sa.Column('base_reps', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'base_reps')
    op.drop_column('exercise', 'base_sets')
    # ### end Alembic commands ###
